import type { Surah } from './schemas';

// Complete Surah metadata for all 114 Surahs
export const surahData: Surah[] = [
  { number: 1, name: "الفاتحة", englishName: "Al-Fatihah", englishNameTranslation: "The Opening", ayahCount: 7, revelationPlace: "Mecca", juzNumbers: [1] },
  { number: 2, name: "البقرة", englishName: "Al-Baqarah", englishNameTranslation: "The Cow", ayahCount: 286, revelationPlace: "Medina", juzNumbers: [1, 2, 3] },
  { number: 3, name: "آل عمران", englishName: "Ali 'Imran", englishNameTranslation: "Family of Imran", ayahCount: 200, revelationPlace: "Medina", juzNumbers: [3, 4] },
  { number: 4, name: "النساء", englishName: "An-Nisa", englishNameTranslation: "The Women", ayahCount: 176, revelationPlace: "Medina", juzNumbers: [4, 5, 6] },
  { number: 5, name: "المائدة", englishName: "Al-Ma'idah", englishNameTranslation: "The Table Spread", ayahCount: 120, revelationPlace: "Medina", juzNumbers: [6, 7] },
  { number: 6, name: "الأنعام", englishName: "Al-An'am", englishNameTranslation: "The Cattle", ayahCount: 165, revelationPlace: "Mecca", juzNumbers: [7, 8] },
  { number: 7, name: "الأعراف", englishName: "Al-A'raf", englishNameTranslation: "The Heights", ayahCount: 206, revelationPlace: "Mecca", juzNumbers: [8, 9] },
  { number: 8, name: "الأنفال", englishName: "Al-Anfal", englishNameTranslation: "The Spoils of War", ayahCount: 75, revelationPlace: "Medina", juzNumbers: [9, 10] },
  { number: 9, name: "التوبة", englishName: "At-Tawbah", englishNameTranslation: "The Repentance", ayahCount: 129, revelationPlace: "Medina", juzNumbers: [10, 11] },
  { number: 10, name: "يونس", englishName: "Yunus", englishNameTranslation: "Jonah", ayahCount: 109, revelationPlace: "Mecca", juzNumbers: [11] },
  { number: 11, name: "هود", englishName: "Hud", englishNameTranslation: "Hud", ayahCount: 123, revelationPlace: "Mecca", juzNumbers: [11, 12] },
  { number: 12, name: "يوسف", englishName: "Yusuf", englishNameTranslation: "Joseph", ayahCount: 111, revelationPlace: "Mecca", juzNumbers: [12, 13] },
  { number: 13, name: "الرعد", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", ayahCount: 43, revelationPlace: "Medina", juzNumbers: [13] },
  { number: 14, name: "إبراهيم", englishName: "Ibrahim", englishNameTranslation: "Abraham", ayahCount: 52, revelationPlace: "Mecca", juzNumbers: [13] },
  { number: 15, name: "الحجر", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", ayahCount: 99, revelationPlace: "Mecca", juzNumbers: [14] },
  { number: 16, name: "النحل", englishName: "An-Nahl", englishNameTranslation: "The Bee", ayahCount: 128, revelationPlace: "Mecca", juzNumbers: [14] },
  { number: 17, name: "الإسراء", englishName: "Al-Isra", englishNameTranslation: "The Night Journey", ayahCount: 111, revelationPlace: "Mecca", juzNumbers: [15] },
  { number: 18, name: "الكهف", englishName: "Al-Kahf", englishNameTranslation: "The Cave", ayahCount: 110, revelationPlace: "Mecca", juzNumbers: [15, 16] },
  { number: 19, name: "مريم", englishName: "Maryam", englishNameTranslation: "Mary", ayahCount: 98, revelationPlace: "Mecca", juzNumbers: [16] },
  { number: 20, name: "طه", englishName: "Taha", englishNameTranslation: "Ta-Ha", ayahCount: 135, revelationPlace: "Mecca", juzNumbers: [16] },
  { number: 21, name: "الأنبياء", englishName: "Al-Anbiya", englishNameTranslation: "The Prophets", ayahCount: 112, revelationPlace: "Mecca", juzNumbers: [17] },
  { number: 22, name: "الحج", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", ayahCount: 78, revelationPlace: "Medina", juzNumbers: [17] },
  { number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", englishNameTranslation: "The Believers", ayahCount: 118, revelationPlace: "Mecca", juzNumbers: [18] },
  { number: 24, name: "النور", englishName: "An-Nur", englishNameTranslation: "The Light", ayahCount: 64, revelationPlace: "Medina", juzNumbers: [18] },
  { number: 25, name: "الفرقان", englishName: "Al-Furqan", englishNameTranslation: "The Criterion", ayahCount: 77, revelationPlace: "Mecca", juzNumbers: [18, 19] },
  { number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", englishNameTranslation: "The Poets", ayahCount: 227, revelationPlace: "Mecca", juzNumbers: [19] },
  { number: 27, name: "النمل", englishName: "An-Naml", englishNameTranslation: "The Ant", ayahCount: 93, revelationPlace: "Mecca", juzNumbers: [19, 20] },
  { number: 28, name: "القصص", englishName: "Al-Qasas", englishNameTranslation: "The Stories", ayahCount: 88, revelationPlace: "Mecca", juzNumbers: [20] },
  { number: 29, name: "العنكبوت", englishName: "Al-'Ankabut", englishNameTranslation: "The Spider", ayahCount: 69, revelationPlace: "Mecca", juzNumbers: [20, 21] },
  { number: 30, name: "الروم", englishName: "Ar-Rum", englishNameTranslation: "The Romans", ayahCount: 60, revelationPlace: "Mecca", juzNumbers: [21] },
  { number: 31, name: "لقمان", englishName: "Luqman", englishNameTranslation: "Luqman", ayahCount: 34, revelationPlace: "Mecca", juzNumbers: [21] },
  { number: 32, name: "السجدة", englishName: "As-Sajdah", englishNameTranslation: "The Prostration", ayahCount: 30, revelationPlace: "Mecca", juzNumbers: [21] },
  { number: 33, name: "الأحزاب", englishName: "Al-Ahzab", englishNameTranslation: "The Combined Forces", ayahCount: 73, revelationPlace: "Medina", juzNumbers: [21, 22] },
  { number: 34, name: "سبأ", englishName: "Saba", englishNameTranslation: "Sheba", ayahCount: 54, revelationPlace: "Mecca", juzNumbers: [22] },
  { number: 35, name: "فاطر", englishName: "Fatir", englishNameTranslation: "Originator", ayahCount: 45, revelationPlace: "Mecca", juzNumbers: [22] },
  { number: 36, name: "يس", englishName: "Ya-Sin", englishNameTranslation: "Ya Sin", ayahCount: 83, revelationPlace: "Mecca", juzNumbers: [22, 23] },
  { number: 37, name: "الصافات", englishName: "As-Saffat", englishNameTranslation: "Those Who Set The Ranks", ayahCount: 182, revelationPlace: "Mecca", juzNumbers: [23] },
  { number: 38, name: "ص", englishName: "Sad", englishNameTranslation: "The Letter Sad", ayahCount: 88, revelationPlace: "Mecca", juzNumbers: [23] },
  { number: 39, name: "الزمر", englishName: "Az-Zumar", englishNameTranslation: "The Troops", ayahCount: 75, revelationPlace: "Mecca", juzNumbers: [23, 24] },
  { number: 40, name: "غافر", englishName: "Ghafir", englishNameTranslation: "The Forgiver", ayahCount: 85, revelationPlace: "Mecca", juzNumbers: [24] },
  { number: 41, name: "فصلت", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", ayahCount: 54, revelationPlace: "Mecca", juzNumbers: [24, 25] },
  { number: 42, name: "الشورى", englishName: "Ash-Shura", englishNameTranslation: "The Consultation", ayahCount: 53, revelationPlace: "Mecca", juzNumbers: [25] },
  { number: 43, name: "الزخرف", englishName: "Az-Zukhruf", englishNameTranslation: "The Ornaments of Gold", ayahCount: 89, revelationPlace: "Mecca", juzNumbers: [25] },
  { number: 44, name: "الدخان", englishName: "Ad-Dukhan", englishNameTranslation: "The Smoke", ayahCount: 59, revelationPlace: "Mecca", juzNumbers: [25] },
  { number: 45, name: "الجاثية", englishName: "Al-Jathiyah", englishNameTranslation: "The Crouching", ayahCount: 37, revelationPlace: "Mecca", juzNumbers: [25] },
  { number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", englishNameTranslation: "The Wind-Curved Sandhills", ayahCount: 35, revelationPlace: "Mecca", juzNumbers: [26] },
  { number: 47, name: "محمد", englishName: "Muhammad", englishNameTranslation: "Muhammad", ayahCount: 38, revelationPlace: "Medina", juzNumbers: [26] },
  { number: 48, name: "الفتح", englishName: "Al-Fath", englishNameTranslation: "The Victory", ayahCount: 29, revelationPlace: "Medina", juzNumbers: [26] },
  { number: 49, name: "الحجرات", englishName: "Al-Hujurat", englishNameTranslation: "The Rooms", ayahCount: 18, revelationPlace: "Medina", juzNumbers: [26] },
  { number: 50, name: "ق", englishName: "Qaf", englishNameTranslation: "The Letter Qaf", ayahCount: 45, revelationPlace: "Mecca", juzNumbers: [26] },
  { number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", englishNameTranslation: "The Winnowing Winds", ayahCount: 60, revelationPlace: "Mecca", juzNumbers: [26, 27] },
  { number: 52, name: "الطور", englishName: "At-Tur", englishNameTranslation: "The Mount", ayahCount: 49, revelationPlace: "Mecca", juzNumbers: [27] },
  { number: 53, name: "النجم", englishName: "An-Najm", englishNameTranslation: "The Star", ayahCount: 62, revelationPlace: "Mecca", juzNumbers: [27] },
  { number: 54, name: "القمر", englishName: "Al-Qamar", englishNameTranslation: "The Moon", ayahCount: 55, revelationPlace: "Mecca", juzNumbers: [27] },
  { number: 55, name: "الرحمن", englishName: "Ar-Rahman", englishNameTranslation: "The Beneficent", ayahCount: 78, revelationPlace: "Medina", juzNumbers: [27] },
  { number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", englishNameTranslation: "The Inevitable", ayahCount: 96, revelationPlace: "Mecca", juzNumbers: [27] },
  { number: 57, name: "الحديد", englishName: "Al-Hadid", englishNameTranslation: "The Iron", ayahCount: 29, revelationPlace: "Medina", juzNumbers: [27] },
  { number: 58, name: "المجادلة", englishName: "Al-Mujadila", englishNameTranslation: "The Pleading Woman", ayahCount: 22, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 59, name: "الحشر", englishName: "Al-Hashr", englishNameTranslation: "The Exile", ayahCount: 24, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", englishNameTranslation: "She That Is To Be Examined", ayahCount: 13, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 61, name: "الصف", englishName: "As-Saf", englishNameTranslation: "The Ranks", ayahCount: 14, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", englishNameTranslation: "The Congregation, Friday", ayahCount: 11, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 63, name: "المنافقون", englishName: "Al-Munafiqun", englishNameTranslation: "The Hypocrites", ayahCount: 11, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 64, name: "التغابن", englishName: "At-Taghabun", englishNameTranslation: "The Mutual Disillusion", ayahCount: 18, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 65, name: "الطلاق", englishName: "At-Talaq", englishNameTranslation: "The Divorce", ayahCount: 12, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 66, name: "التحريم", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", ayahCount: 12, revelationPlace: "Medina", juzNumbers: [28] },
  { number: 67, name: "الملك", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", ayahCount: 30, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 68, name: "القلم", englishName: "Al-Qalam", englishNameTranslation: "The Pen", ayahCount: 52, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 69, name: "الحاقة", englishName: "Al-Haqqah", englishNameTranslation: "The Reality", ayahCount: 52, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 70, name: "المعارج", englishName: "Al-Ma'arij", englishNameTranslation: "The Ascending Stairways", ayahCount: 44, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 71, name: "نوح", englishName: "Nuh", englishNameTranslation: "Noah", ayahCount: 28, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 72, name: "الجن", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", ayahCount: 28, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 73, name: "المزمل", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", ayahCount: 20, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 74, name: "المدثر", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", ayahCount: 56, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 75, name: "القيامة", englishName: "Al-Qiyamah", englishNameTranslation: "The Resurrection", ayahCount: 40, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 76, name: "الإنسان", englishName: "Al-Insan", englishNameTranslation: "The Man", ayahCount: 31, revelationPlace: "Medina", juzNumbers: [29] },
  { number: 77, name: "المرسلات", englishName: "Al-Mursalat", englishNameTranslation: "The Emissaries", ayahCount: 50, revelationPlace: "Mecca", juzNumbers: [29] },
  { number: 78, name: "النبأ", englishName: "An-Naba", englishNameTranslation: "The Tidings", ayahCount: 40, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 79, name: "النازعات", englishName: "An-Nazi'at", englishNameTranslation: "Those Who Drag Forth", ayahCount: 46, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 80, name: "عبس", englishName: "'Abasa", englishNameTranslation: "He Frowned", ayahCount: 42, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 81, name: "التكوير", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", ayahCount: 29, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 82, name: "الانفطار", englishName: "Al-Infitar", englishNameTranslation: "The Cleaving", ayahCount: 19, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 83, name: "المطففين", englishName: "Al-Mutaffifin", englishNameTranslation: "The Defrauding", ayahCount: 36, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", englishNameTranslation: "The Sundering", ayahCount: 25, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 85, name: "البروج", englishName: "Al-Buruj", englishNameTranslation: "The Mansions of the Stars", ayahCount: 22, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 86, name: "الطارق", englishName: "At-Tariq", englishNameTranslation: "The Nightcomer", ayahCount: 17, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 87, name: "الأعلى", englishName: "Al-A'la", englishNameTranslation: "The Most High", ayahCount: 19, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", englishNameTranslation: "The Overwhelming", ayahCount: 26, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 89, name: "الفجر", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", ayahCount: 30, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 90, name: "البلد", englishName: "Al-Balad", englishNameTranslation: "The City", ayahCount: 20, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 91, name: "الشمس", englishName: "Ash-Shams", englishNameTranslation: "The Sun", ayahCount: 15, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 92, name: "الليل", englishName: "Al-Layl", englishNameTranslation: "The Night", ayahCount: 21, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 93, name: "الضحى", englishName: "Ad-Duhaa", englishNameTranslation: "The Morning Hours", ayahCount: 11, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 94, name: "الشرح", englishName: "Ash-Sharh", englishNameTranslation: "The Relief", ayahCount: 8, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 95, name: "التين", englishName: "At-Tin", englishNameTranslation: "The Fig", ayahCount: 8, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 96, name: "العلق", englishName: "Al-'Alaq", englishNameTranslation: "The Clot", ayahCount: 19, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 97, name: "القدر", englishName: "Al-Qadr", englishNameTranslation: "The Power", ayahCount: 5, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 98, name: "البينة", englishName: "Al-Bayyinah", englishNameTranslation: "The Clear Proof", ayahCount: 8, revelationPlace: "Medina", juzNumbers: [30] },
  { number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", englishNameTranslation: "The Earthquake", ayahCount: 8, revelationPlace: "Medina", juzNumbers: [30] },
  { number: 100, name: "العاديات", englishName: "Al-'Adiyat", englishNameTranslation: "The Courser", ayahCount: 11, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 101, name: "القارعة", englishName: "Al-Qari'ah", englishNameTranslation: "The Calamity", ayahCount: 11, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 102, name: "التكاثر", englishName: "At-Takathur", englishNameTranslation: "The Rivalry in World Increase", ayahCount: 8, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 103, name: "العصر", englishName: "Al-'Asr", englishNameTranslation: "The Declining Day", ayahCount: 3, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 104, name: "الهمزة", englishName: "Al-Humazah", englishNameTranslation: "The Traducer", ayahCount: 9, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 105, name: "الفيل", englishName: "Al-Fil", englishNameTranslation: "The Elephant", ayahCount: 5, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 106, name: "قريش", englishName: "Quraysh", englishNameTranslation: "Quraysh", ayahCount: 4, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 107, name: "الماعون", englishName: "Al-Ma'un", englishNameTranslation: "The Small Kindnesses", ayahCount: 7, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 108, name: "الكوثر", englishName: "Al-Kawthar", englishNameTranslation: "The Abundance", ayahCount: 3, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 109, name: "الكافرون", englishName: "Al-Kafirun", englishNameTranslation: "The Disbelievers", ayahCount: 6, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 110, name: "النصر", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", ayahCount: 3, revelationPlace: "Medina", juzNumbers: [30] },
  { number: 111, name: "المسد", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", ayahCount: 5, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", englishNameTranslation: "The Sincerity", ayahCount: 4, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 113, name: "الفلق", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", ayahCount: 5, revelationPlace: "Mecca", juzNumbers: [30] },
  { number: 114, name: "الناس", englishName: "An-Nas", englishNameTranslation: "Mankind", ayahCount: 6, revelationPlace: "Mecca", juzNumbers: [30] },
];

// Curated Daily Ayahs - Beautiful, meaningful verses
export const dailyAyahs = [
  { surah: 2, ayah: 255, theme: "The Throne Verse" }, // Ayatul Kursi
  { surah: 3, ayah: 185, theme: "Life & Death" },
  { surah: 55, ayah: 13, theme: "Gratitude" },
  { surah: 93, ayah: 5, theme: "Hope" },
  { surah: 94, ayah: 6, theme: "Ease After Hardship" },
  { surah: 2, ayah: 286, theme: "Divine Mercy" },
  { surah: 3, ayah: 139, theme: "Strength" },
  { surah: 13, ayah: 28, theme: "Peace of Heart" },
  { surah: 65, ayah: 3, theme: "Trust in Allah" },
  { surah: 2, ayah: 152, theme: "Remembrance" },
  { surah: 9, ayah: 51, theme: "Decree of Allah" },
  { surah: 39, ayah: 53, theme: "Mercy" },
  { surah: 3, ayah: 159, theme: "Trust" },
  { surah: 14, ayah: 7, theme: "Gratitude" },
  { surah: 16, ayah: 97, theme: "Good Life" },
  { surah: 25, ayah: 74, theme: "Family" },
  { surah: 40, ayah: 60, theme: "Prayer" },
  { surah: 49, ayah: 13, theme: "Equality" },
  { surah: 57, ayah: 4, theme: "Divine Presence" },
  { surah: 67, ayah: 2, theme: "Purpose of Life" },
  { surah: 112, ayah: 1, theme: "Oneness of Allah" },
  { surah: 1, ayah: 5, theme: "Seeking Guidance" },
  { surah: 2, ayah: 186, theme: "Allah is Near" },
  { surah: 6, ayah: 162, theme: "Devotion" },
  { surah: 17, ayah: 82, theme: "Quran as Healing" },
  { surah: 21, ayah: 87, theme: "Dua of Yunus" },
  { surah: 23, ayah: 118, theme: "Seeking Mercy" },
  { surah: 28, ayah: 24, theme: "Dua for Good" },
  { surah: 35, ayah: 34, theme: "Gratitude in Paradise" },
  { surah: 36, ayah: 58, theme: "Peace" },
];

// Get daily ayah based on day of year (deterministic)
export function getDailyAyahIndex(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return dayOfYear % dailyAyahs.length;
}

// Juz (Para) data
export const juzData = Array.from({ length: 30 }, (_, i) => ({
  number: i + 1,
  name: `Juz ${i + 1}`,
  arabicName: `الجزء ${i + 1}`,
}));

// Quranic Supplications (Duas) - Only from the Quran
export const quranicDuas = [
  { surah: 1, ayah: 6, theme: "Guidance" },
  { surah: 2, ayah: 127, theme: "Acceptance" },
  { surah: 2, ayah: 128, theme: "Submission" },
  { surah: 2, ayah: 201, theme: "Good in Both Worlds" },
  { surah: 2, ayah: 250, theme: "Patience & Victory" },
  { surah: 2, ayah: 286, theme: "Ease of Burden" },
  { surah: 3, ayah: 8, theme: "Steadfastness" },
  { surah: 3, ayah: 16, theme: "Forgiveness" },
  { surah: 3, ayah: 147, theme: "Steadfastness" },
  { surah: 3, ayah: 191, theme: "Protection from Fire" },
  { surah: 3, ayah: 193, theme: "Forgiveness" },
  { surah: 3, ayah: 194, theme: "Promise of Allah" },
  { surah: 7, ayah: 23, theme: "Repentance" },
  { surah: 7, ayah: 126, theme: "Death as Muslim" },
  { surah: 7, ayah: 156, theme: "Mercy" },
  { surah: 10, ayah: 85, theme: "Protection from Oppressors" },
  { surah: 12, ayah: 101, theme: "Good Death" },
  { surah: 14, ayah: 40, theme: "Prayer & Offspring" },
  { surah: 14, ayah: 41, theme: "Forgiveness" },
  { surah: 17, ayah: 24, theme: "Mercy for Parents" },
  { surah: 17, ayah: 80, theme: "Truthful Entry & Exit" },
  { surah: 18, ayah: 10, theme: "Mercy & Guidance" },
  { surah: 20, ayah: 25, theme: "Ease of Task" },
  { surah: 21, ayah: 87, theme: "Dua of Yunus" },
  { surah: 21, ayah: 89, theme: "Offspring" },
  { surah: 23, ayah: 97, theme: "Protection from Shaytan" },
  { surah: 23, ayah: 109, theme: "Forgiveness & Mercy" },
  { surah: 23, ayah: 118, theme: "Forgiveness & Mercy" },
  { surah: 25, ayah: 74, theme: "Righteous Family" },
  { surah: 27, ayah: 19, theme: "Gratitude" },
  { surah: 28, ayah: 16, theme: "Forgiveness" },
  { surah: 28, ayah: 24, theme: "Need for Good" },
  { surah: 40, ayah: 7, theme: "Forgiveness & Paradise" },
  { surah: 46, ayah: 15, theme: "Gratitude & Righteous Deeds" },
  { surah: 59, ayah: 10, theme: "Forgiveness & Brotherhood" },
  { surah: 60, ayah: 4, theme: "Trust in Allah" },
  { surah: 60, ayah: 5, theme: "Protection from Fitnah" },
  { surah: 66, ayah: 8, theme: "Complete Light" },
  { surah: 71, ayah: 28, theme: "Forgiveness for All" },
];
